spring.application.name=FGAloha

#Datasources
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#JPA
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#Thymeleaf
spring.thymeleaf.cache=false

#Application Settings
ec.banner.message=¥10,000以上で送料無料
ec.free.shipping.threshold=10000

